---
- name: Configure R2
  hosts: R2
  become: true 
  tasks:
     
    - name: Install lynx net-tools epel-release
      yum:
        name:
          - lynx
          - net-tools
          - epel-release
        state: present
      tags:
        - epel-release

    - name: install quagga
      yum:
        name: quagga
        state: present
      tags:
        - quagga

    - name: edit sysctl ip_forward
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

    - name: Manage zebra conf
      template:
        src: templates/R2-zebra.j2
        dest: /etc/quagga/zebra.conf
        owner: root
        group: root
        mode: 0644
      notify: restart zebra

    - name: Manage ospfd conf
      template:
        src: templates/R2-ospfd.j2
        dest: /etc/quagga/ospfd.conf
        owner: root
        group: root
        mode: 0644
      notify: restart ospfd

    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      selinux:
        policy: targeted
        state: permissive

    - name: Start daemon zebra
      systemd: 
        name: zebra
        state: started
        enabled: yes

    - name: Start daemon ospfd
      systemd:
        name: ospfd
        state: started
        enabled: yes

